[package]
name = "nnsdk"
version = "0.3.0"
authors = ["jam1garner <jam@jam1.re>"]
edition = "2018"
license = "MIT"
description = "Cleanroom reverse-engineered bindings for nnsdk (Nintendo Switch SDK)"
documentation = "https://docs.rs/nnsdk"

[dependencies]
libc-nnsdk = "0.3.0"
binrw = "0.11.1"
byteorder = "1.4.3"
serde = { version = "1.0", features = ["derive"] }

# rustc-dep-of-std
core = { version = "1.0.0", optional = true, package = "rustc-std-workspace-core" }
alloc = { version = "1.0.0", optional = true, package = "rustc-std-workspace-alloc" }
compiler_builtins = { version = "0.1", optional = true }

[features]
rustc-dep-of-std = [
    "libc-nnsdk/rustc-dep-of-std",
    "core",
    "alloc",
    "compiler_builtins"
]
