[package]
name = "nnsdk"
version = "0.2.1"
authors = ["jam1garner <jam1.mcleod@hotmail.com>"]
edition = "2018"
license = "MIT"
description = "Cleanroom reverse-engineered bindings for nnsdk (Nintendo Switch SDK)"
documentation = "https://docs.rs/nnsdk"

[dependencies]
libc-nnsdk = "0.2.0"
bitfield-struct = "0.1.8"

# rustc-dep-of-std
core = { version = "1.0.0", optional = true, package = "rustc-std-workspace-core" }
alloc = { version = "1.0.0", optional = true, package = "rustc-std-workspace-alloc" }
compiler_builtins = { version = "0.1", optional = true }

[features]
rustc-dep-of-std = [
    "libc-nnsdk/rustc-dep-of-std",
    "core",
    "alloc",
    "compiler_builtins"
]
